control_configurations:    
  - name: mqtt_watch
    components:
    - {hardware_interface: "mqtt_hw",   controller: "js_pub", description: ""}
    #- {hardware_interface: "ft_hw", controller : "ft_pub", runtime_check: false}
    
  - name: olp_ctrl
    depends: [mqtt_watch]
    hidden: true
    components:
      - { hardware_interface: "mqtt_hw", controller : "p_j"}
      
  - name: impedance_ctrl
    depends: [mqtt_watch]
    hidden: true
    components:
      - { hardware_interface: "mqtt_hw", controller : "cart_impedance_controller"}
      
  - name: def_ctrl
    depends: [olp_ctrl]
    hidden: true
    components:
      - { hardware_interface: "deformation_hw", controller : "deformation_ctrl"}

  - name: planner
    depends: [def_ctrl]
    components:
    - {hardware_interface: "plan_hw", controller: "microint"}
    
  - name: planner_impedance
    depends: [impedance_ctrl]
    components:
    - {hardware_interface: "plan_hw", controller: "microint"}
    
    
    
configuration_dispatches:
  - { name: mqtt_watch,  at: .5 }
  - { name: planner,  at: 1.0 }
  #- { name: planner_impedance,  at: 2.0 }
