mqtt_hw:
  type: "cnr/control/MQTTRobotHW"
  appenders      : [file, screen]
  levels         : [trace, info]
  pattern_layout : "[%5p][%d{HH:mm:ss,SSS}][%50M:%04L][%24c] %m%n"
  file_name      : mqtt_hw
  sampling_period: 0.004
  diagnostic_period: 0.1
  maximum_missing_cycles: 100
  feedback_joint_state_timeout: 10

  joint_names:   
  - joint_0
  - joint_1
  - joint_2
  - joint_3
  - joint_4
  - joint_5
  - joint_6

  base_link: "fake_linear_axis"
  tool_link: "link_6"
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning
  kin_update_period: 0.1

  initial_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  
  max_tracking_error: 1
  verbose: false
  
  use_delta_target_pos: false
  delta_pos_from_start: false
  
  use_real_robot: true
  
  #--- MQTT ---
  
  client_id: "MQTT_HW"
  host: 192.168.125.7    # drapebot
  #host: localhost
  port: 1883
  
  feedback_mqtt_topic: "/robot_1/feedback"
  out_feedback_mqtt_topic: "/ITR_feedback"
  command_mqtt_topic:  "/robot_1/command"
  nominal_trajectory_topic: /joint_pos_target
  
  use_json: true
  # --- end ---
  

  remap_source_args:
  - "/mqtt_hw/js_pub/joint_states"
  remap_target_args:
  - "/joint_states"


  js_pub:
    type: cnr/control/JointStatePublisher
    controlled_joints: all
    kin_update_period : 0.004


  p_j:
    type: cnr/control/OpenLoopPositionController
    setpoint_topic_name: /joint_pos_target
    controlled_joints: all
    kin_update_period : 0.004
  
  deformation_ctrl:
    type: "cnr/control/DeformationCtrl"
    controlled_joints: all
    kin_update_period: 0.004
    
    use_cartesian_reference: false                 # are you going to use a reference Pose or JointState?  default: false
    joint_target_topic:     "/joint_pos_target"   # incoming joints setpoint topic 
    pose_target:            "/interp_target_cart_pose"   # incoming pose setpoint topic
    
    robot_base_frame  : fake_linear_axis
    robot_tip_frame   : link_6
    
    
  gt_traj_arb:
    type: cnr/control/GTTrajArbitration
    controlled_joints: [ joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
    
    kin_update_period: 0.04
    
    robot_base_frame  : base_link
    robot_tip_frame   : grasping
    force_sensor_frame: grasping
    
    use_cartesian_reference: false
    joint_target_topic:     "/joint_pos_target"
    pose_target:            "/target_cart_pose"
    
    external_wrench_topic: "/deformation_estimation"
    wrench_deadband: [.05,.03,.02,1,1,0.05]
    use_filtered_wrench: true
    omega_wrench: 1000
    #wrench_gains: [100,100,100,1,1,2]
    wrench_gains: [0,0,10,0,0,0]
    
    set_wrench_zero: true
    wrench_zero: [0,0.9,0,0,0,0]  # measured in meters from the gripper
    
    ### for GT and MG
    M_r: [10,10,1,.1,.1,.1]
    K_r: [0,0,0,0,0,0]
    D_r: [100,100,100,1,1,5]
    damping_is_ratio: false

    
    #n_dofs: 3
    
    #Qhh: [1,1,1,0.0001,0.0001,0.0001]
    #Qhr: [0,0,0,0,0,0]
    
    #Qrh: [0,0,0,0,0,0]
    #Qrr: [1,1,1,0.0001,0.0001,0.0001]
    
    #Rh: [0.0005,0.0005,0.0005]
    #Rr: [0.0001,0.0001,0.0001]
    
    #mask: [1,1,1,0,0,0]
    
    
    n_dofs: 6
    
    Qhh: [1,1,1,1,1,1,0.0001,0.0001,0.0001,0.0001,0.0001,0.0001]
    Qhr: [0,0,0,0,0,0,0,0,0,0,0,0]
    
    Qrh: [0,0,0,0,0,0,0,0,0,0,0,0]
    Qrr: [1,1,1,1,1,1,0.0001,0.0001,0.0001,0.0001,0.0001,0.0001]
    
    Rh: [0.0005,0.0005,0.0005,0.5,0.5,5]
    #Rh: [0.00005,0.00005,0.00005,1,1,1]
    
    Rr: [0.0005,0.0005,0.0005,0.5,0.5,5]
    
    mask: [1,1,1,0,0,1]
    
    
    robot_active: true   # true for GT - false for MG and IC
        
    alpha: 0.99
    alpha_max: 0.99
    alpha_min: 0.01
    alpha_switch: 0.5
    
    base_control: "cgt"
    #control_switch: "ncgt"
    control_switch: "inverse_cgt"
    use_same_reference: false
    use_robot_reference: false
    use_human_reference: true



plan_hw:
  type: cnr/control/TopicRobotHW
  appenders: [file, screen]
  levels: [trace, info]
  pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
  file_name: "plan_hw"
  
  joint_names:   
  - joint_0
  - joint_1
  - joint_2
  - joint_3
  - joint_4
  - joint_5
  - joint_6

  base_link: "fake_linear_axis"
  tool_link: "link_6"
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning

  feedback_joint_state_topic: /joint_states
  command_joint_state_topic:  /joint_pos_target
  sampling_period: 0.004
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20
  maximum_missing_cycles: 100

  remap_source_args:
  - "/plan_hw/microint/follow_joint_trajectory/cancel"
  - "/plan_hw/microint/follow_joint_trajectory/feedback"
  - "/plan_hw/microint/follow_joint_trajectory/goal"
  - "/plan_hw/microint/follow_joint_trajectory/result"
  - "/plan_hw/microint/follow_joint_trajectory/status"

  remap_target_args:
  - "abb_moveit_lab/follow_joint_trajectory/cancel"
  - "abb_moveit_lab/follow_joint_trajectory/feedback"
  - "abb_moveit_lab/follow_joint_trajectory/goal"
  - "abb_moveit_lab/follow_joint_trajectory/result"
  - "abb_moveit_lab/follow_joint_trajectory/status"

  microint____:
    type: "cnr/control/FollowJointTrajectoryPosVelEffController"
    controlled_joints: all
    interpolator: "thor/ThorPrefilter"
    regulator: "regulator/fake_regulator"
    spline_order: 1
    
    
  microint:
    type: "cnr/control/ScaledFJTPosController"
    controlled_joints: all


  
  
  
  
  
