action_name: "/abb_moveit_lab/follow_joint_trajectory"
mqtt_topic: "/robot_1/joint_trajectory"
broker_address: "192.168.125.7"
port: 1883
client_id: mqtt_converter
rate: 100

joint_names: 
- joint_0
- joint_1
- joint_2
- joint_3
- joint_4
- joint_5
- joint_6




