base_frame: "world"
tool_frame: "gripper"
test_links:
- end_effector

minimum_distance: 0.2
reaction_time: 0.15 

#Information to publish obstacles
publish_obstacles: true
sphere_radius: 0.2
sphere_rgba: [1.0,1.0,1.0,0.2]

minimum_distance: 0.3  # optional (default: 0.3). Minimal distance (meter), if slower the robot will stop
maximum_cartesian_acceleration: 0.1  # optional (default: 0.1). Maximum cartesian acceleration (m/s^2)
